"""
Image Generation Service - AI-powered image generation for posts

This service generates images using DALL-E 3 based on post content:
1. Generate images from post text
2. Download generated images
3. Upload to Supabase Storage
4. Return public URLs
"""

import logging
import os
import io
import requests
from typing import Optional
from fastapi import HTTPException, status, UploadFile
from openai import OpenAI

from services.storage_service import get_storage_service
from config.settings import settings

logger = logging.getLogger(__name__)


class ImageGenerationService:
    """
    Service for generating images using DALL-E 3 API.

    Usage:
        image_service = ImageGenerationService()
        url = await image_service.generate_from_post_content(post_text, user_id)
    """

    def __init__(self):
        """Initialize image generation service"""
        self.api_key = settings.OPENAI_API_KEY
        if not self.api_key:
            raise ValueError("OPENAI_API_KEY not configured")

        self.client = OpenAI(api_key=self.api_key)
        self.storage_service = get_storage_service()
        logger.info("✅ Image generation service initialized (DALL-E 3)")

    def _summarize_text(self, text: str, max_length: int = 200) -> str:
        """
        Summarize text if it's too long for DALL-E prompt.

        Args:
            text: Text to summarize
            max_length: Maximum length for summary

        Returns:
            Summarized text
        """
        if len(text) <= max_length:
            return text

        # Simple truncation with ellipsis
        # Future: Could use LLM for smarter summarization
        return text[:max_length].rsplit(' ', 1)[0] + "..."

    def _build_dalle_prompt(self, post_text: str) -> str:
        """
        Build DALL-E prompt from post content.

        Args:
            post_text: Post text content

        Returns:
            DALL-E prompt optimized for LinkedIn posts
        """
        summary = self._summarize_text(post_text, max_length=200)

        prompt = (
            f"Create a professional, clean LinkedIn post image about: {summary}. "
            f"Modern business style, minimal text, visually appealing, "
            f"suitable for professional social media. "
            f"High quality, photorealistic or abstract design."
        )

        return prompt

    async def generate_from_post_content(
        self,
        post_text: str,
        user_id: str
    ) -> str:
        """
        Generate image from post content using DALL-E 3.

        Args:
            post_text: Post text content
            user_id: User's UUID (for file organization)

        Returns:
            Public URL of generated and uploaded image

        Raises:
            HTTPException: If generation or upload fails
        """
        # Validate input
        if not post_text or not post_text.strip():
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Please write some content before generating an image"
            )

        if len(post_text.strip()) < 20:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Post content too short. Write at least 20 characters."
            )

        try:
            # Build DALL-E prompt
            dalle_prompt = self._build_dalle_prompt(post_text)
            logger.info(f"🎨 Generating image for user {user_id}")
            logger.info(f"📝 DALL-E prompt: {dalle_prompt[:100]}...")

            # Call DALL-E 3 API
            response = self.client.images.generate(
                model="dall-e-3",
                prompt=dalle_prompt,
                size="1024x1024",
                quality="standard",
                n=1
            )

            # Get image URL from response
            if not response.data or len(response.data) == 0:
                raise HTTPException(
                    status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                    detail="DALL-E returned no images"
                )

            dalle_image_url = response.data[0].url
            logger.info(f"✅ Image generated by DALL-E: {dalle_image_url[:50]}...")

            # Download image from DALL-E URL
            logger.info("📥 Downloading generated image...")
            image_response = requests.get(dalle_image_url, timeout=30)
            image_response.raise_for_status()

            image_bytes = image_response.content
            image_size = len(image_bytes)
            logger.info(f"✅ Image downloaded ({image_size} bytes)")

            # Convert to UploadFile format for storage service
            # DALL-E returns PNG images
            image_file = io.BytesIO(image_bytes)

            # Create UploadFile-like object
            class DallEImageFile:
                def __init__(self, file_bytes: bytes):
                    self.file = io.BytesIO(file_bytes)
                    self.filename = "dalle_generated.png"
                    self.content_type = "image/png"

                async def read(self):
                    return self.file.read()

            upload_file = DallEImageFile(image_bytes)

            # Upload to Supabase using existing storage service
            logger.info("☁️  Uploading to Supabase Storage...")
            public_url = await self.storage_service.upload_image(
                upload_file,
                user_id
            )

            logger.info(f"✅ Image uploaded successfully: {public_url[:50]}...")
            return public_url

        except HTTPException:
            raise
        except requests.RequestException as e:
            logger.error(f"❌ Failed to download DALL-E image: {str(e)}")
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Failed to download generated image"
            )
        except Exception as e:
            logger.error(f"❌ Image generation failed: {str(e)}")
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=f"Failed to generate image: {str(e)}"
            )


# Singleton instance
_image_service: Optional[ImageGenerationService] = None


def get_image_service() -> ImageGenerationService:
    """
    Get or create the global image generation service instance.

    Returns:
        Image generation service instance
    """
    global _image_service
    if _image_service is None:
        _image_service = ImageGenerationService()
    return _image_service
